### ISSUE TITLE
    from bs4 import BeautifulSoup ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by Foksiu** [CrystalxCode/HentaiFetcher#1]
So, I had everything from my requirements text file installed, but it keeps saying there's no bs4 from beautifulSoup
rain pls fix

**Comment by CrystalxCode** [comment]
What's your Python version and pip version?

``python --version`` or ``python3 --version``
``pip --version`` or ``pip3 --version``

**Comment by CrystalxCode** [comment]
This has been inactive for a couple of days, I will be closing this issue. Feel free to reopen it.
